# Generated by Django 3.2.3 on 2021-05-21 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_image', models.ImageField(upload_to='post_content_images_for_articles/')),
            ],
        ),
        migrations.CreateModel(
            name='ArticlePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images_for_articles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameModel(
            old_name='Reply',
            new_name='ArticleReply',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='ArticleCategory',
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='ArticleComment',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='ArticleTag',
        ),
        migrations.DeleteModel(
            name='ContentImage',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='articlepost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.articlecategory'),
        ),
        migrations.AddField(
            model_name='articlepost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='articles.ArticleTag'),
        ),
        migrations.AddField(
            model_name='articlecontentimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.articlepost'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.articlepost'),
        ),
    ]
