# Generated by Django 3.2.3 on 2021-05-21 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210521_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontentimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images_of_article_post', to='articles.articlepost'),
        ),
    ]
