# Generated by Django 3.2.3 on 2021-05-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articlecontentimage_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='content',
            new_name='content_0',
        ),
        migrations.AddField(
            model_name='articlepost',
            name='content_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlepost',
            name='content_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlepost',
            name='content_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
