# Generated by Django 3.2.3 on 2021-05-19 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mypage', '0003_auto_20210519_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageBetweenUserAndUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('send_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='message send date')),
                ('receive_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_received_from_user', to=settings.AUTH_USER_MODEL)),
                ('send_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sent_for_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザー間のメッセージ',
                'verbose_name_plural': '研究室-ユーザー間のメッセージ一覧',
            },
        ),
        migrations.CreateModel(
            name='ChatMessageBetweenUserAndLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('send_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='message send date')),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_with_user', to='mypage.laboratory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_with_lab', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '研究室-ユーザー間のメッセージ',
                'verbose_name_plural': '研究室-ユーザー間のメッセージ一覧',
            },
        ),
    ]
