# Generated by Django 3.1.2 on 2021-05-13 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '学科・専攻',
                'verbose_name_plural': '学科・専攻一覧',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '学部',
                'verbose_name_plural': '学部一覧',
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory_name', models.CharField(max_length=100)),
                ('create_date', models.DateField(auto_now=True)),
                ('belong_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_in_department', to='mypage.department')),
                ('belong_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_in_faculty', to='mypage.faculty')),
            ],
            options={
                'verbose_name': '研究室',
                'verbose_name_plural': '研究室一覧',
            },
        ),
        migrations.CreateModel(
            name='UniversityArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_area', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '都道府県',
                'verbose_name_plural': '都道府県一覧',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('university_system', models.IntegerField(choices=[(0, '国立'), (1, '公立'), (2, '私立'), (3, 'その他')], verbose_name='大学法人')),
                ('university_website', models.URLField(blank=True)),
                ('university_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_in_area', to='mypage.universityarea')),
            ],
            options={
                'verbose_name': '大学',
                'verbose_name_plural': '大学一覧',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('kind_of_notification', models.CharField(max_length=100)),
                ('create_date', models.DateField(auto_now=True)),
                ('notification_detail', models.TextField()),
                ('laboratory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_for_laboratory', to='mypage.laboratory')),
            ],
            options={
                'verbose_name': '通知メッセージ',
                'verbose_name_plural': '通知メッセージ一覧',
            },
        ),
        migrations.AddField(
            model_name='laboratory',
            name='belong_university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_in_university', to='mypage.university'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='belong_university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_in_university', to='mypage.university'),
        ),
        migrations.CreateModel(
            name='ExaminationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_date', models.DateField(blank=True, null=True)),
                ('detail_info', models.TextField()),
                ('page_create_date', models.DateField(auto_now=True)),
                ('page_update_date', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examination_info', to='mypage.department')),
            ],
            options={
                'verbose_name': '学科・専攻入試情報',
                'verbose_name_plural': '学科・専攻入試情報一覧',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='belong_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_in_faculty', to='mypage.faculty'),
        ),
    ]
