# Generated by Django 3.1.2 on 2021-05-13 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsForLaboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('kind_of_notification', models.CharField(max_length=100)),
                ('create_date', models.DateField(auto_now=True)),
                ('notification_detail', models.TextField()),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_for_laboratory', to='mypage.laboratory')),
                ('send_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_for_laboratory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '研究室通知メッセージ',
                'verbose_name_plural': '研究室通知メッセージ一覧',
            },
        ),
        migrations.CreateModel(
            name='NotificationsForUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('kind_of_notification', models.CharField(max_length=100)),
                ('create_date', models.DateField(auto_now=True)),
                ('notification_detail', models.TextField()),
                ('send_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_for_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_for_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通知メッセージ',
                'verbose_name_plural': '通知メッセージ一覧',
            },
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
