# Generated by Django 3.1.2 on 2021-05-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_researchpaper_paper_kind'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_laboratory',
            field=models.ManyToManyField(blank=True, related_name='person_favorite_laboratory_info', to='search.LaboratoryInfo', verbose_name='お気に入り研究室'),
        ),
    ]
