# Generated by Django 3.1.2 on 2021-05-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_laboratory',
            field=models.ManyToManyField(blank=True, to='search.Laboratory', verbose_name='お気に入りの場所'),
        ),
    ]
