# Generated by Django 3.1.2 on 2021-05-05 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='upload_laboratory',
        ),
    ]
