# Generated by Django 3.1.2 on 2021-05-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210514_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_laboratory_notification',
            field=models.BooleanField(default=True, verbose_name='お気に入り登録の通知'),
        ),
    ]
