# Generated by Django 3.1.2 on 2021-04-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory_name', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('university_website', models.URLField(blank=True)),
                ('faculty', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('department_website', models.URLField(blank=True)),
                ('campus', models.CharField(blank=True, max_length=100)),
                ('professor_name', models.CharField(max_length=100)),
                ('all_student_count', models.IntegerField(blank=True, default=0)),
                ('master_count', models.IntegerField(blank=True, default=0)),
                ('doctor_count', models.IntegerField(blank=True, default=0)),
                ('after_graduation', models.CharField(blank=True, max_length=100)),
                ('research_keywords', models.CharField(blank=True, max_length=100)),
                ('research_info', models.TextField()),
                ('laboratory_website', models.URLField(blank=True)),
                ('entrance_examination_date', models.TextField(blank=True)),
                ('master_acceptance', models.BooleanField(null=True)),
                ('doctor_acceptance', models.BooleanField(null=True)),
                ('adult_graduate_student_acceptance', models.BooleanField(null=True)),
                ('degree_of_difficulty', models.IntegerField(blank=True, default=0)),
                ('environment', models.IntegerField(blank=True, default=0)),
                ('students_rate', models.IntegerField(blank=True, default=0)),
                ('Employment_rate', models.IntegerField(blank=True, default=0)),
                ('free_comment', models.TextField(blank=True)),
                ('create_date', models.DateField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('information_source', models.URLField()),
            ],
            options={
                'verbose_name': '研究室',
                'verbose_name_plural': '研究室一覧',
            },
        ),
    ]
