# Generated by Django 3.1.2 on 2021-05-13 05:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mypage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_website', models.URLField(blank=True)),
                ('campus', models.CharField(blank=True, max_length=100)),
                ('professor_name', models.CharField(max_length=100)),
                ('all_student_count', models.IntegerField(blank=True, default=0)),
                ('master_count', models.IntegerField(blank=True, default=0)),
                ('doctor_count', models.IntegerField(blank=True, default=0)),
                ('after_graduation', models.CharField(blank=True, max_length=100)),
                ('research_keywords', models.CharField(blank=True, max_length=100)),
                ('research_info', models.TextField()),
                ('laboratory_website', models.URLField(blank=True)),
                ('entrance_examination_date', models.TextField(blank=True)),
                ('entrance_examination_info', models.TextField(blank=True)),
                ('master_acceptance', models.BooleanField(null=True)),
                ('doctor_acceptance', models.BooleanField(null=True)),
                ('adult_graduate_student_acceptance', models.BooleanField(null=True)),
                ('degree_of_difficulty', models.IntegerField(blank=True, default=0)),
                ('environment', models.IntegerField(blank=True, default=0)),
                ('students_rate', models.IntegerField(blank=True, default=0)),
                ('Employment_rate', models.IntegerField(blank=True, default=0)),
                ('free_comment', models.TextField(blank=True)),
                ('page_create_date', models.DateField(auto_now=True)),
                ('page_update_date', models.DateTimeField(auto_now=True)),
                ('information_source', models.URLField()),
                ('confirmation', models.BooleanField(null=True)),
                ('laboratory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_of_laboratory', to='mypage.laboratory')),
            ],
            options={
                'verbose_name': '記載研究室',
                'verbose_name_plural': '記載研究室一覧',
            },
        ),
        migrations.CreateModel(
            name='SearchText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_item', models.CharField(max_length=100, verbose_name='検索ワード')),
            ],
            options={
                'verbose_name': '検索ワード',
                'db_table': 'search',
            },
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.CharField(max_length=100, verbose_name='論文タイトル')),
                ('paper_info', models.TextField(blank=True)),
                ('paper_file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='研究論文')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_paper', to='search.laboratoryinfo')),
                ('paper_uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_paper', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '論文',
                'db_table': 'research_paper',
            },
        ),
    ]
