# Generated by Django 3.1.2 on 2021-04-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_item', models.CharField(max_length=100, verbose_name='検索ワード')),
            ],
            options={
                'verbose_name': '検索ワード',
                'db_table': 'search',
            },
        ),
        migrations.AddField(
            model_name='laboratory',
            name='confirmation',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='entrance_examination_info',
            field=models.TextField(blank=True),
        ),
    ]
