# Generated by Django 3.1.2 on 2021-05-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='paper_kind',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='論文の種類'),
        ),
    ]
