# Generated by Django 3.1.2 on 2021-04-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210428_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='university_area',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='university_system',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
