# Generated by Django 3.2.3 on 2021-05-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210520_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratoryinfo',
            name='picture_1',
        ),
        migrations.RemoveField(
            model_name='laboratoryinfo',
            name='picture_2',
        ),
        migrations.RemoveField(
            model_name='laboratoryinfo',
            name='picture_3',
        ),
    ]
