# Generated by Django 3.1.2 on 2021-05-05 04:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_laboratory_uploader'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.CharField(max_length=100, verbose_name='論文タイトル')),
                ('paper_info', models.TextField(blank=True)),
                ('paper_file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='研究論文')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_uploader', to='search.laboratory')),
            ],
            options={
                'verbose_name': '論文',
                'db_table': 'research_paper',
            },
        ),
    ]
