# Generated by Django 3.1.2 on 2021-05-05 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_researchpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper_uploader', to='search.laboratory'),
        ),
    ]
